/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

/**
 *
 * @author Rofi Setiawan
 */

import koneksi.koneksi;
import java.sql.*;
import javax.swing.*;
public class login extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet rs;
    String sql;
        
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        koneksi DB = new koneksi();
        DB.config();
        con = DB.con;
        stm = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        Pas = new javax.swing.JPasswordField();
        tombol_Login = new javax.swing.JButton();
        tombol_Batal = new javax.swing.JButton();
        tombol_BuatAkun = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().
            getResource("/menu/bntech.jpg")).getImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
    jLabel1.setText("FORM LOGIN");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

    jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
    jLabel2.setText("USERNAME");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, -1, -1));

    jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
    jLabel3.setText("PASSWORD");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 240, -1, -1));

    User.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            UserActionPerformed(evt);
        }
    });
    getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 189, 170, -1));

    Pas.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            PasActionPerformed(evt);
        }
    });
    getContentPane().add(Pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 239, 170, -1));

    tombol_Login.setText("LOGIN");
    tombol_Login.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tombol_LoginActionPerformed(evt);
        }
    });
    getContentPane().add(tombol_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(745, 307, -1, -1));

    tombol_Batal.setText("BATAL");
    tombol_Batal.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tombol_BatalActionPerformed(evt);
        }
    });
    getContentPane().add(tombol_Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(852, 307, -1, -1));

    tombol_BuatAkun.setText("BUAT AKUN");
    tombol_BuatAkun.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tombol_BuatAkunActionPerformed(evt);
        }
    });
    getContentPane().add(tombol_BuatAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(783, 348, -1, -1));

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/Login.png"))); // NOI18N
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasActionPerformed

    private void tombol_BuatAkunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_BuatAkunActionPerformed
        // TODO add your handling code here:
        dispose();
        Registrasi r = new Registrasi();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombol_BuatAkunActionPerformed

    private void tombol_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_BatalActionPerformed
        // TODO add your handling code here:
        User.setText("");
        Pas.setText("");
    }//GEN-LAST:event_tombol_BatalActionPerformed

    private void tombol_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombol_LoginActionPerformed
        // TODO add your handling code here:
        try {
           sql = "select * from users where username ='"+User.getText()+"' and password='"+Pas.getText()+"'";
           rs = stm.executeQuery(sql);
           if(rs.next()){
               JOptionPane.showMessageDialog(this,"Selamat datang "+User.getText());
               dispose();
            menu r = new menu();
            r.setVisible(true);
            this.setVisible(false);
           }
           else{
               JOptionPane.showMessageDialog(this,"Username atau Password anda salah");
               User.setText("");
               Pas.setText("");
           }
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_tombol_LoginActionPerformed

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Pas;
    private javax.swing.JTextField User;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton tombol_Batal;
    private javax.swing.JButton tombol_BuatAkun;
    private javax.swing.JButton tombol_Login;
    // End of variables declaration//GEN-END:variables

    private static class menutama {

        public menutama() {
        }

        private void show() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
