/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;
import koneksi.MyConnection;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Rofi Setiawan
 */
public class menu_logistic extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu_logistic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        tombol_Master = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        tombol_Laporan = new javax.swing.JMenu();
        lap_BarangKeluar = new javax.swing.JMenuItem();
        lap_BarangMasuk = new javax.swing.JMenuItem();
        lap_Supplier = new javax.swing.JMenuItem();
        lap_Customer = new javax.swing.JMenuItem();
        tombolKeluar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().
            getResource("/menu/bntech.jpg")).getImage());
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
    jLabel1.setText("MENU UTAMA LOGISTIC");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 88));

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu/menu.png"))); // NOI18N
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

    tombol_Master.setText("Master");

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem2.setText("Barang_keluar");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    tombol_Master.add(jMenuItem2);

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
    jMenuItem3.setText("Barang_Masuk");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    tombol_Master.add(jMenuItem3);

    jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
    jMenuItem5.setText("Customer");
    jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem5ActionPerformed(evt);
        }
    });
    tombol_Master.add(jMenuItem5);

    jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
    jMenuItem6.setText("Supplier");
    jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem6ActionPerformed(evt);
        }
    });
    tombol_Master.add(jMenuItem6);

    jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
    jMenuItem7.setText("Transaksi");
    jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem7ActionPerformed(evt);
        }
    });
    tombol_Master.add(jMenuItem7);

    jMenuBar2.add(tombol_Master);

    tombol_Laporan.setText("Laporan");

    lap_BarangKeluar.setText("Laporan Barang Keluar");
    lap_BarangKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            lap_BarangKeluarMouseClicked(evt);
        }
    });
    lap_BarangKeluar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            lap_BarangKeluarActionPerformed(evt);
        }
    });
    tombol_Laporan.add(lap_BarangKeluar);

    lap_BarangMasuk.setText("Laporan Barang Masuk");
    lap_BarangMasuk.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            lap_BarangMasukActionPerformed(evt);
        }
    });
    tombol_Laporan.add(lap_BarangMasuk);

    lap_Supplier.setText("Laporan Supplier");
    lap_Supplier.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            lap_SupplierActionPerformed(evt);
        }
    });
    tombol_Laporan.add(lap_Supplier);

    lap_Customer.setText("Laporan Customer");
    lap_Customer.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            lap_CustomerActionPerformed(evt);
        }
    });
    tombol_Laporan.add(lap_Customer);

    jMenuBar2.add(tombol_Laporan);

    tombolKeluar.setText("Keluar");
    tombolKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            tombolKeluarMouseClicked(evt);
        }
    });
    tombolKeluar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            tombolKeluarActionPerformed(evt);
        }
    });
    jMenuBar2.add(tombolKeluar);

    setJMenuBar(jMenuBar2);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new transaksi().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void tombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKeluarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tombolKeluarActionPerformed

    private void tombolKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolKeluarMouseClicked
        // TODO add your handling code here:
        dispose();
        login_logistic r = new login_logistic();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolKeluarMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new barang_keluar().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new barang_masuk().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new customer().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new supplier().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void lap_BarangKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lap_BarangKeluarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lap_BarangKeluarMouseClicked

    private void lap_BarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_BarangKeluarActionPerformed
        // TODO add your handling code here:
    try{
            String file = "E:\\Materi Kuliah\\Materi Semester 6\\Pemrograman Visual\\Project_Bntech\\src\\Laporan\\laporanbarangkeluar.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, MyConnection.getConnection());
            JasperViewer.viewReport(jp);

        } catch (Exception e){
        }
    }//GEN-LAST:event_lap_BarangKeluarActionPerformed

    private void lap_BarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_BarangMasukActionPerformed
        // TODO add your handling code here:
        try{
            String file = "E:\\Materi Kuliah\\Materi Semester 6\\Pemrograman Visual\\Project_Bntech\\src\\Laporan\\laporanbarangmasuk.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, MyConnection.getConnection());
            JasperViewer.viewReport(jp);

        } catch (Exception e){
        }
    }//GEN-LAST:event_lap_BarangMasukActionPerformed

    private void lap_SupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_SupplierActionPerformed
        // TODO add your handling code here:
        try{
            String file = "E:\\Materi Kuliah\\Materi Semester 6\\Pemrograman Visual\\Project_Bntech\\src\\Laporan\\laporansupplier.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, MyConnection.getConnection());
            JasperViewer.viewReport(jp);

        } catch (Exception e){
        }
    }//GEN-LAST:event_lap_SupplierActionPerformed

    private void lap_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lap_CustomerActionPerformed
        // TODO add your handling code here:
        try{
            String file = "E:\\Materi Kuliah\\Materi Semester 6\\Pemrograman Visual\\Project_Bntech\\src\\Laporan\\laporancustomer.jrxml";
            JasperReport jr = JasperCompileManager.compileReport(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, MyConnection.getConnection());
            JasperViewer.viewReport(jp);

        } catch (Exception e){
        }
    }//GEN-LAST:event_lap_CustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_logistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_logistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_logistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_logistic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_logistic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem lap_BarangKeluar;
    private javax.swing.JMenuItem lap_BarangMasuk;
    private javax.swing.JMenuItem lap_Customer;
    private javax.swing.JMenuItem lap_Supplier;
    private javax.swing.JMenu tombolKeluar;
    private javax.swing.JMenu tombol_Laporan;
    private javax.swing.JMenu tombol_Master;
    // End of variables declaration//GEN-END:variables
}
